# Generated by Django 3.2.16 on 2023-08-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otherproducts',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mrfppartno', models.TextField(blank=True, db_column='MrfpPartNo', null=True)),
                ('datasheet', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, db_column='REF', null=True)),
                ('mounting', models.TextField(blank=True, db_column='Mounting', null=True)),
                ('value', models.TextField(blank=True, db_column='VALUE', null=True)),
                ('ht', models.TextField(blank=True, db_column='HT', null=True)),
                ('dia', models.TextField(blank=True, db_column='Dia', null=True)),
                ('spring_dia', models.TextField(blank=True, db_column='Spring_Dia', null=True)),
                ('material', models.TextField(blank=True, db_column='Material', null=True)),
                ('pitch', models.TextField(blank=True, db_column='Pitch', null=True)),
                ('three_d_drawing', models.TextField(blank=True, db_column='Three_d_drawing', null=True)),
                ('size_of_component', models.TextField(blank=True, db_column='Size_of_component', null=True)),
            ],
            options={
                'db_table': 'OtherProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surfaceproducts',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mrfppartno', models.TextField(blank=True, db_column='MrfpPartNo', null=True)),
                ('datasheet', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, db_column='REF', null=True)),
                ('mounting', models.TextField(blank=True, db_column='Mounting', null=True)),
                ('value', models.TextField(blank=True, db_column='VALUE', null=True)),
                ('ht', models.TextField(blank=True, db_column='HT', null=True)),
                ('dia', models.TextField(blank=True, db_column='Dia', null=True)),
                ('spring_dia', models.TextField(blank=True, db_column='Spring_Dia', null=True)),
                ('material', models.TextField(blank=True, db_column='Material', null=True)),
                ('pitch', models.TextField(blank=True, db_column='Pitch', null=True)),
                ('three_d_drawing', models.TextField(blank=True, db_column='Three_d_drawing', null=True)),
                ('size_of_component', models.TextField(blank=True, db_column='Size_of_component', null=True)),
            ],
            options={
                'db_table': 'SurfaceProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Throughproducts',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mrfppartno', models.TextField(blank=True, db_column='MrfpPartNo', null=True)),
                ('datasheet', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, db_column='REF', null=True)),
                ('mounting', models.TextField(blank=True, db_column='Mounting', null=True)),
                ('value', models.TextField(blank=True, db_column='VALUE', null=True)),
                ('ht', models.TextField(blank=True, db_column='HT', null=True)),
                ('dia', models.TextField(blank=True, db_column='Dia', null=True)),
                ('spring_dia', models.TextField(blank=True, db_column='Spring_Dia', null=True)),
                ('material', models.TextField(blank=True, db_column='Material', null=True)),
                ('pitch', models.TextField(blank=True, db_column='Pitch', null=True)),
                ('three_d_drawing', models.TextField(blank=True, db_column='Three_d_drawing', null=True)),
                ('size_of_component', models.TextField(blank=True, db_column='Size_of_component', null=True)),
            ],
            options={
                'db_table': 'ThroughProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChalanTable',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('chalanno', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('products', models.TextField(blank=True, null=True)),
                ('prices', models.TextField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('url1', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chalantable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='name', null=True)),
                ('company_name', models.TextField(blank=True, db_column='company_name', null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone1', models.CharField(blank=True, db_column='phone1', max_length=20, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
